wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.16.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742537728.0
    t:
      1:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.9.21
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
